CREATE TABLE Sensor
(
    name varchar(30) PRIMARY KEY UNIQUE
);

CREATE TABLE Measurement
(
    id          int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    value       numeric(5, 2) NOT NULL,
    raining     boolean       NOT NULL,
    measured_at timestamp,
    sensor_name varchar(30) references Sensor (name) on delete cascade
);
